// <auto-generated />
using System;
using BountyHunters.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BountyHunters.Data.Migrations
{
    [DbContext(typeof(BountyHuntersDbContext))]
    partial class BountyHuntersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BountyHunters.Data.Models.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BountyHunterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAchieved")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BountyHunterId");

                    b.ToTable("Achievements", (string)null);
                });

            modelBuilder.Entity("BountyHunters.Data.Models.BountyHunter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CaptureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("BountyHunters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b1d56b1-f46d-4225-8976-c9c70bff5801"),
                            Bio = "A new bounty hunter ready for action.",
                            CaptureCount = 0,
                            Name = "John Tracker",
                            Rank = "Novice"
                        },
                        new
                        {
                            Id = new Guid("fe4401e8-927d-4ed4-92ee-414b00904977"),
                            Bio = "Experienced bounty hunter with countless captures.",
                            CaptureCount = 8,
                            Name = "Jane Swift",
                            Rank = "Expert"
                        },
                        new
                        {
                            Id = new Guid("763bb5a4-65ca-445f-adee-846098ca0b57"),
                            Bio = "New bounty hunter",
                            CaptureCount = 0,
                            Name = "Alice Tracker",
                            Rank = "Novice"
                        },
                        new
                        {
                            Id = new Guid("8f8651c0-7c6c-4e6b-81d7-dbecd1e433bd"),
                            Bio = "Seasoned hunter.",
                            CaptureCount = 10,
                            Name = "Bob Hunter",
                            Rank = "Expert"
                        });
                });

            modelBuilder.Entity("BountyHunters.Data.Models.Capture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BountyHunterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CaptureDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CriminalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BountyHunterId");

                    b.HasIndex("CriminalId");

                    b.ToTable("Captures", (string)null);
                });

            modelBuilder.Entity("BountyHunters.Data.Models.Criminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Bounty")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CaptureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrimeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Criminals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e449bd86-5d5e-49b9-8c5e-5bc882b440b7"),
                            Bounty = 10000m,
                            CrimeType = "Hacking",
                            Name = "Eve Rogue",
                            Status = "At Large"
                        },
                        new
                        {
                            Id = new Guid("6de37a14-f172-420b-a87a-075d12d6d799"),
                            Bounty = 5000m,
                            CrimeType = "Bank Robbery",
                            Name = "John Doe",
                            Status = "At Large"
                        },
                        new
                        {
                            Id = new Guid("dddad914-41a0-4525-a4c3-520b74310dfd"),
                            Bounty = 3000m,
                            CrimeType = "Fraud",
                            Name = "Jane Smith",
                            Status = "At Large"
                        });
                });

            modelBuilder.Entity("BountyHunters.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BountyHunters.Data.Models.Achievement", b =>
                {
                    b.HasOne("BountyHunters.Data.Models.BountyHunter", "BountyHunter")
                        .WithMany("Achievements")
                        .HasForeignKey("BountyHunterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BountyHunter");
                });

            modelBuilder.Entity("BountyHunters.Data.Models.Capture", b =>
                {
                    b.HasOne("BountyHunters.Data.Models.BountyHunter", "BountyHunter")
                        .WithMany("Captures")
                        .HasForeignKey("BountyHunterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BountyHunters.Data.Models.Criminal", "Criminal")
                        .WithMany("Captures")
                        .HasForeignKey("CriminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BountyHunter");

                    b.Navigation("Criminal");
                });

            modelBuilder.Entity("BountyHunters.Data.Models.BountyHunter", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Captures");
                });

            modelBuilder.Entity("BountyHunters.Data.Models.Criminal", b =>
                {
                    b.Navigation("Captures");
                });
#pragma warning restore 612, 618
        }
    }
}
